name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Extract version from tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Setup Bun runtime
        uses: oven-sh/setup-bun@v2

      - name: Install project dependencies
        run: bun install

      - name: Build production assets
        run: bun run build:assets

      - name: Prepare release artifact
        run: |
          mv dist all-in-one-assets
          zip -r all-in-one-assets.zip all-in-one-assets/

      - name: Collect additional release files
        id: release_files
        run: |
          extra_files=$(find ./all-in-one-assets -type f \( -name "*.txt" -o -name "*.json" -o -name "*.md" -o -name "*.csv" \)) 
          echo "files<<EOF" >> $GITHUB_ENV
          echo "$extra_files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            all-in-one-assets.zip
            ${{ env.files }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
